apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv # Name of the PersistentVolume resource

spec:
  capacity:
    storage: 1Gi # Total storage allocated for this PV
  accessModes:
    - ReadWriteOnce # This volume can be mounted by one node in read-write mode
  hostPath:
    path: "/mnt/data" # Directory on the node used as backing storage (for learning/local setup)
  