apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc # Request name for the storage claim

spec:
  accessModes:
    - ReadWriteOnce # The app wants storage that can be used by one node in read-write mode
  resources:
    requests:
      storage: 512Mi # Amount of storage requested by the Pod
  volumeMode: Filesystem # Storage is treated as a filesystem mount
  
